# Generated by Django 3.1.2 on 2021-04-27 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=130)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JObDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('experience', models.TextField()),
                ('skills', models.TextField()),
                ('app_dedline', models.TextField()),
                ('published', models.DateTimeField()),
                ('categoryfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='BekarJubok.categoryfield')),
                ('jobcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='BekarJubok.jobcategory')),
            ],
        ),
        migrations.AddField(
            model_name='categoryfield',
            name='jobcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BekarJubok.jobcategory'),
        ),
    ]
