# Generated by Django 3.1.2 on 2021-05-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BekarJubok', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='categoryfield',
            new_name='position',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='company',
            field=models.CharField(default='Google', max_length=200),
        ),
    ]
