# Generated by Django 3.1.2 on 2021-05-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BekarJubok', '0004_auto_20210503_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
