# Generated by Django 3.1.2 on 2021-05-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BekarJubok', '0005_auto_20210503_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='position',
            field=models.CharField(default='Software Engineer', max_length=200),
        ),
        migrations.DeleteModel(
            name='CategoryField',
        ),
    ]
